package com.gbraille.keyboard.database;

import android.database.sqlite.SQLiteDatabase;

public class DicionarioPTBRLetraX {
	public DicionarioPTBRLetraX(DbHelper dbh, SQLiteDatabase db){
		dicionarioLetraX(dbh, db);
	}
	
	private void dicionarioLetraX(DbHelper dbh, SQLiteDatabase db){
		db.execSQL( dbh.createInsertDicionario("x", "vigésima quarta letra do alfabeto latino usado em português") );
		db.execSQL( dbh.createInsertDicionario("xá", "monarcas iranianos que antecederam a revolução islâmica de 1979, cuja origem remonta à dinastia aquemênida.") );
		db.execSQL( dbh.createInsertDicionario("xabre", "terra arenosa, areia grossa. argaço, xebra.") );
		db.execSQL( dbh.createInsertDicionario("xácara", "narrativa popular em verso") );
		db.execSQL( dbh.createInsertDicionario("xacra", "centro de energias corporais") );
		db.execSQL( dbh.createInsertDicionario("xador", "véu usado por mulheres em países muçulmanos, que deixa apenas os olhos à mostra") );
		db.execSQL( dbh.createInsertDicionario("xadrez", "jogo de estratégia para dois jogadores, jogado num tabuleiro com 64 quadrados, alternados claros e escuros. Cada jogador possui 16 peças: oito peões, duas torres, dois cavalos, dois bispos, uma dama e um rei; o objetivo do jogo é dar xeque-mate ao rei adversário") );
		db.execSQL( dbh.createInsertDicionario("xadrezar", "dispor em forma de xadrez, enxadrezar") );
		db.execSQL( dbh.createInsertDicionario("xadrezista", "jogador de xadrez") );
		db.execSQL( dbh.createInsertDicionario("xaile", "grafia alternativa de xale") );
		db.execSQL( dbh.createInsertDicionario("xairel", "cobertura para animal doméstico, de tecido ou de couro, sobre a qual é colocada a sela ou a albarda") );
		db.execSQL( dbh.createInsertDicionario("xale", "peça de roupa usada como cobertura dos ombros, de forma não presa") );
		db.execSQL( dbh.createInsertDicionario("xamanismo", "sistema de magia e exorcismo usado por povos primitivos") );
		db.execSQL( dbh.createInsertDicionario("xamanista", "indivíduo que pratica o xamanismo") );
		db.execSQL( dbh.createInsertDicionario("xamate", "xeque-mate") );
		db.execSQL( dbh.createInsertDicionario("Xambioá", "município brasileiro do estado do Tocantins") );
		db.execSQL( dbh.createInsertDicionario("Xambrê", "município brasileiro do estado do Paraná") );
		db.execSQL( dbh.createInsertDicionario("xâmego", "bate-coxa (dançar coladinho). abraço; troca de carinho. namoro.") );
		db.execSQL( dbh.createInsertDicionario("xampu", "produto líquido especial para lavar a cabeça") );
		db.execSQL( dbh.createInsertDicionario("xana", "vagina, órgão genital feminino") );
		db.execSQL( dbh.createInsertDicionario("Xanadu", "capital de verão do império de Kublai Khan") );
		db.execSQL( dbh.createInsertDicionario("Xandi", "Forma de apelido dado para pessoas, que possuem o nome próprio Alexandre.") );
		db.execSQL( dbh.createInsertDicionario("xangaiense", "de ou relativo a Xangai - cidade da China") );
		db.execSQL( dbh.createInsertDicionario("xangaiês", "de ou relativo a Xangai - cidade da China") );
		db.execSQL( dbh.createInsertDicionario("Xangô", "nome de um orixá poderoso das religiões afro-brasileiras") );
		db.execSQL( dbh.createInsertDicionario("Xangri-lá", "município brasileiro do estado do Rio Grande do Sul") );
		db.execSQL( dbh.createInsertDicionario("xantina", "composto orgânico encontrado na urina e em diversos tecidos do corpo humano, além de algumas plantas") );
		db.execSQL( dbh.createInsertDicionario("xantofila", "pigmento amarelo nas folhas de alguns vegetais") );
		db.execSQL( dbh.createInsertDicionario("xantogênico", "relativo ao vírus da febre amarela") );
		db.execSQL( dbh.createInsertDicionario("xantopsia", "perturbação visual na qual todos os objetos observados aparentam ter cor amarela") );
		db.execSQL( dbh.createInsertDicionario("Xanxerê", "município brasileiro do estado de Santa Catarina") );
		db.execSQL( dbh.createInsertDicionario("Xapuri", "município brasileiro do estado do Acre") );
		db.execSQL( dbh.createInsertDicionario("xaputa", "peixe da família dos Corífenídeos, bastante comum na costa portuguesa") );
		db.execSQL( dbh.createInsertDicionario("xará", "pessoa com mesmo nome de outrem; homônimo; tocaio. chapa; camarada.") );
		db.execSQL( dbh.createInsertDicionario("xara", "flecha de madeira queimada") );
		db.execSQL( dbh.createInsertDicionario("xaramago", " planta da espécie Sisymbrium officinale, conhecida também como saramago-rinchão. ") );
		db.execSQL( dbh.createInsertDicionario("xarda", "alcunha que se dá às judias. peixe perciforme, da família dos escombrídeos. sarda, efélide.") );
		db.execSQL( dbh.createInsertDicionario("xardo", "alcunha que se dá aos judeus") );
		db.execSQL( dbh.createInsertDicionario("xardoso", "que tem xardas, que tem efélides.") );
		db.execSQL( dbh.createInsertDicionario("xarel", "o mesmo que xairel") );
		db.execSQL( dbh.createInsertDicionario("xarém", " farinha de milho. papas de milho. tipo de dança.") );
		db.execSQL( dbh.createInsertDicionario("xarifa", "órgão genital feminino") );
		db.execSQL( dbh.createInsertDicionario("xarola", "andor de procissão. órgão genital feminino.") );
		db.execSQL( dbh.createInsertDicionario("xarolo", "órgão genital feminino. mulherio.") );
		db.execSQL( dbh.createInsertDicionario("xarondar", "enxotar") );
		db.execSQL( dbh.createInsertDicionario("xaropar", "tratar com xarope") );
		db.execSQL( dbh.createInsertDicionario("xarope", "mistura de certos líquidos com açúcar. pessoa chata. pessoa que faz desatinos, coisas desarrazoadas que vão contra o bom senso.") );
		db.execSQL( dbh.createInsertDicionario("xarumelas", "criança que chora muito") );
		db.execSQL( dbh.createInsertDicionario("xastre", "o mesmo que alfaiate") );
		db.execSQL( dbh.createInsertDicionario("xata", "filha da vaca e do touro, bezerra") );
		db.execSQL( dbh.createInsertDicionario("xato", "filhote da vaca e do touro, bezerro") );
		db.execSQL( dbh.createInsertDicionario("xaual", "décimo mês do calendário islâmico") );
		db.execSQL( dbh.createInsertDicionario("xavante", "de ou relativo à Xavantes, cidade de São Paulo (Brasil)") );
		db.execSQL( dbh.createInsertDicionario("xavantense", "de ou relativo à Xavantes - cidade de São Paulo (Brasil)") );
		db.execSQL( dbh.createInsertDicionario("Xavantina", "município brasileiro do estado de Santa Catarina") );
		db.execSQL( dbh.createInsertDicionario("xavantino", "habitante ou natural de Xavantes - cidade de São Paulo (Brasil)") );
		db.execSQL( dbh.createInsertDicionario("xaveco", "pequena embarcação. barco pequeno e mal construído ou velho; embarcação ordinária.") );
		db.execSQL( dbh.createInsertDicionario("Xavier", "prenome masculino.") );
		db.execSQL( dbh.createInsertDicionario("xaxado", "dança nordestina") );
		db.execSQL( dbh.createInsertDicionario("xaxar", "preparar a terra para que possa ser plantada") );
		db.execSQL( dbh.createInsertDicionario("xaxim", "feto arborescente, da família das dicksoniáceas, nativo da Mata Atlântica e América Central") );
		db.execSQL( dbh.createInsertDicionario("xebra", "voz com a que os pastores provocam que o gado do rebanho comum se separe, cada um para a sua casa") );
		db.execSQL( dbh.createInsertDicionario("xebrar", "separar os animais uns dos outros. selecionar, escolher o fruto, separando qualidades. separar, delimitar, estremar.") );
		db.execSQL( dbh.createInsertDicionario("xebre", "voz que açula aos animais a separarem-se para as suas diferentes casas quando volta o rebanho comum.") );
		db.execSQL( dbh.createInsertDicionario("xebroada", "abundância de argaços trazidos pelo mar, abundância de algas para adubo das terras de cultivo.") );
		db.execSQL( dbh.createInsertDicionario("xeleléu", "bajulador") );
		db.execSQL( dbh.createInsertDicionario("xelim", "moeda inglesa de prata que representava 1/20 da libra esterlina, até 1971") );
		db.execSQL( dbh.createInsertDicionario("xenão", "elemento químico de símbolo Xe. Também é conhecido como xénon em Portugal. xenônio.") );
		db.execSQL( dbh.createInsertDicionario("xenobiótico", "substâncias químicas estranhas a um organismo ou sistema biológico") );
		db.execSQL( dbh.createInsertDicionario("xenofilia", "amor ou estima às pessoas e coisas estrangeiras") );
		db.execSQL( dbh.createInsertDicionario("xenófilo", "Que sente admiração ou simpatia pelo que é estrangeiro.") );
		db.execSQL( dbh.createInsertDicionario("xenófoba", "feminino de xenófobo") );
		db.execSQL( dbh.createInsertDicionario("xenofobia", "antipatia pelas pessoas ou coisas estrangeiras") );
		db.execSQL( dbh.createInsertDicionario("xenofóbico", "qualidade relativa ao medo daquilo que é estrangeiro. que tem xenofobia.") );
		db.execSQL( dbh.createInsertDicionario("xenófobo", "que tem aversão ao que é estrangeiro") );
		db.execSQL( dbh.createInsertDicionario("xênon", "xenônio") );
		db.execSQL( dbh.createInsertDicionario("xénon", "xenônio") );
		db.execSQL( dbh.createInsertDicionario("xenónio", "elemento químico de número atómico 54 e símbolo Xe.") );
		db.execSQL( dbh.createInsertDicionario("xenônio", "elemento químico de número atómico 54 e símbolo Xe.") );
		db.execSQL( dbh.createInsertDicionario("xenreira", " ira, rancor, irritação. zanga, inimizade, antipatia.") );
		db.execSQL( dbh.createInsertDicionario("xepa", "mercadoria de qualidade inferior vendida a preço baixo ao final da feira.") );
		db.execSQL( dbh.createInsertDicionario("xepeiro", " indivíduo que vive pedindo as coisas. quem vive de recursos alheios. quem vai aos locais sem ser convidado.") );
		db.execSQL( dbh.createInsertDicionario("xeque", "chefe beduíno. soberano, líder, homem mais velho da tribo.íder espiritual do sufismo.lance no jogo de xadrez em que o rei está sob ameaça. acontecimento parlamentar que envolve perigo para o governo.") );
		db.execSQL( dbh.createInsertDicionario("xeque-mate", "lance numa partida de xadrez em que se ataca o rei adversário de maneira que ele não possa mais escapar, ocasionando a derrota do lado que recebe esse xeque") );
		db.execSQL( dbh.createInsertDicionario("xereca", "um dos muitos nomes populares para o órgão genital feminino") );
		db.execSQL( dbh.createInsertDicionario("xerém", "o mesmo que xarém") );
		db.execSQL( dbh.createInsertDicionario("xereta", "bisbilhoteiro; intrometido") );
		db.execSQL( dbh.createInsertDicionario("xeretar", "bisbilhotar") );
		db.execSQL( dbh.createInsertDicionario("xerez", "espécie de uva preta. certo vinho típico da Andaluzia.") );
		db.execSQL( dbh.createInsertDicionario("xerife", "título usado por príncipes mouros. magistrado em certas povoações de países da América Ocidental.") );
		db.execSQL( dbh.createInsertDicionario("xerimbabo", "animal de estimação") );
		db.execSQL( dbh.createInsertDicionario("xerocar", "produzir fotocópias") );
		db.execSQL( dbh.createInsertDicionario("xerografia", "técnica através da qual são obtidas cópias de imagens e/ou textos através de fotoestimulação em uma máquina com a seguinte impressão numa folha de papel.") );
		db.execSQL( dbh.createInsertDicionario("xerox", "máquina usada na reprodução de texto ou imagem.") );
		db.execSQL( dbh.createInsertDicionario("xérox", "máquina empregada para fazer fotocópias. a própria fotocópia.") );
		db.execSQL( dbh.createInsertDicionario("xetá", "Indivíduo do povo tupi-guarani que habitou o estado do Paraná, Brasil. Língua tupi-guarani extinta que já foi falada pelos xetás..") );
		db.execSQL( dbh.createInsertDicionario("Xexéu", "município brasileiro do estado de Pernambuco") );
		db.execSQL( dbh.createInsertDicionario("xhosa", "grupo étnico sul-africano. idioma desse grupo.") );
		db.execSQL( dbh.createInsertDicionario("xibaba", "maconha") );
		db.execSQL( dbh.createInsertDicionario("xibé", "alimento de raiz indígena, consumido na região amazônica; é uma mistura de água com farinha de mandioca que pode ser degustado puro ou com pirarucu e outros peixes, fritos ou assados, como também charque") );
		db.execSQL( dbh.createInsertDicionario("xibungo", "homossexual masculino passivo") );
		db.execSQL( dbh.createInsertDicionario("xícara", "o mesmo que chávena.o conteúdo de uma xícara.") );
		db.execSQL( dbh.createInsertDicionario("xifópago", "característica de gêmeos que nascem unidos por partes do corpo, usualmente na altura do tórax, pelo apêndice xifóide. diz-se de pessoas que mantém uma união muito forte.") );
		db.execSQL( dbh.createInsertDicionario("xiita", "partidário das convicções religiosas e políticas do xiismo; chiita. que é radicalmente obcesso em suas convicções. radical e ardoroso.") );
		db.execSQL( dbh.createInsertDicionario("xilado", "intoxicado com bebida alcoólica; alcoolizado, bêbado") );
		db.execSQL( dbh.createInsertDicionario("xilarmônico", "espécie de marimba") );
		db.execSQL( dbh.createInsertDicionario("xilema", "tecido das plantas vasculares por onde circula a seiva desde a raiz até às folhas") );
		db.execSQL( dbh.createInsertDicionario("xílgaro", "pintassilgo-comum") );
		db.execSQL( dbh.createInsertDicionario("xilindró", "cadeia; delegacia") );
		db.execSQL( dbh.createInsertDicionario("xilofone", " instrumento de percussão constituído por lâminas de madeira de tamanhos diversos de modo a reproduzir as escalas musicais quando percutidos por baquetas") );
		db.execSQL( dbh.createInsertDicionario("xilógrafo", "pessoa que faz xilografia.") );
		db.execSQL( dbh.createInsertDicionario("ximbé", "que tem o focinho ou o nariz achatado") );
		db.execSQL( dbh.createInsertDicionario("ximbeva", "que tem o focinho ou o nariz achatado") );
		db.execSQL( dbh.createInsertDicionario("ximbica", "cachaça. calhambeque. fiteiro. vulva. casa especializada em apostas. jogo de cartas.") );
		db.execSQL( dbh.createInsertDicionario("ximbra", "pequena esfera vítrea usada no jogo de gude; bolinha") );
		db.execSQL( dbh.createInsertDicionario("xingamento", "ação de xingar") );
		db.execSQL( dbh.createInsertDicionario("xingar", "dirigir insultos ou palavras afrontosas; falar mal de alguém") );
		db.execSQL( dbh.createInsertDicionario("Xinguara", "município brasileiro do estado do Pará") );
		db.execSQL( dbh.createInsertDicionario("xintoísmo", "antiga religião politeísta do Japão, de origem autóctone e ainda professada nos dias atuais") );
		db.execSQL( dbh.createInsertDicionario("xipaia", "Indivíduo do povo indígena tupi que habita os rios Iriri e Curuá e a cidade de Altamira, Pará, Brasil. Língua tupi aparentada do juruna falada pelos xipaias.") );
		db.execSQL( dbh.createInsertDicionario("xique-xique", "planta nativa da caatinga") );
		db.execSQL( dbh.createInsertDicionario("xiquexique", "tipo de chocalho.  o mesmo que bicho-de-pé.") );
		db.execSQL( dbh.createInsertDicionario("xiranha", "órgão sexual feminino") );
		db.execSQL( dbh.createInsertDicionario("xirê", "festa pública de orixá que acontece em um terreiro") );
		db.execSQL( dbh.createInsertDicionario("xiri", "vagina") );
		db.execSQL( dbh.createInsertDicionario("Xis", "nome do fuso horário que está onze horas a menos do que o Meridiano de Greenwich (UTC−11)") );
		db.execSQL( dbh.createInsertDicionario("xisto", " rocha metamórfica cujos minerais são visíveis a olho nu, e que tem um aspecto folheado") );
		db.execSQL( dbh.createInsertDicionario("xistra", "pequeno ramo para guiar o gado, jostra. árvore da espécie Sorbus aucuparia, tramazeira. fenômeno meteorológico, vento frio e forte com bátegas de auga-neve, ou neve. xisto, lousa.") );
		db.execSQL( dbh.createInsertDicionario("xistro", "instrumento usado para raspar tártaro dos dentes") );
		db.execSQL( dbh.createInsertDicionario("xixi", "urina. planta faseolácea cuja seiva serve de verniz.") );
		db.execSQL( dbh.createInsertDicionario("xixo", "cubos de carne temperados, colocados no espeto e assados") );
		db.execSQL( dbh.createInsertDicionario("xó", "usa-se para deter os animais de tiro ou de cavalgadura") );
		db.execSQL( dbh.createInsertDicionario("xô", "usa-se para xotar, para fazer fugir aos animais. comunica a vontade a alguém que este deixe um local, distancie-se.") );
		db.execSQL( dbh.createInsertDicionario("xocar", "enxotar galinhas ou outras aves") );
		db.execSQL( dbh.createInsertDicionario("xofre", " elemento cujos átomos têm 16 prótons em seu núcleo.") );
		db.execSQL( dbh.createInsertDicionario("xona", "indivíduo do povo xona, da África. língua desse povo.") );
		db.execSQL( dbh.createInsertDicionario("xorca", "adorno em forma de argola e com moedas usado nos braços e nas pernas. calçado grande.") );
		db.execSQL( dbh.createInsertDicionario("xordo", "surdo. manco.") );
		db.execSQL( dbh.createInsertDicionario("xostrão", "prisão policial") );
		db.execSQL( dbh.createInsertDicionario("xota", "vulva") );
		db.execSQL( dbh.createInsertDicionario("xotar", "o mesmo que enxotar") );
		db.execSQL( dbh.createInsertDicionario("xote", " dança de salão acompanhada de sanfonas.") );
		db.execSQL( dbh.createInsertDicionario("xouva", "sardinha pequena.") );
		db.execSQL( dbh.createInsertDicionario("xoxo", "beijoca") );
		db.execSQL( dbh.createInsertDicionario("xoxota", "vulva, vagina") );
		db.execSQL( dbh.createInsertDicionario("xpto", "de boa qualidade; ótimo; designação grega de Cristo.") );
		db.execSQL( dbh.createInsertDicionario("xuá", "cesta realizada sem que a bola toque no aro.  som vocálico neutro átono e não-tonal usado em algumas línguas.  algo muito bom; maravilha.") );
		db.execSQL( dbh.createInsertDicionario("xuatê", "chocalho cerimonial usado por índios em ritauis religiosos") );
		db.execSQL( dbh.createInsertDicionario("xucro", "selvagem") );
		db.execSQL( dbh.createInsertDicionario("xumbregar", "bolinar") );
		db.execSQL( dbh.createInsertDicionario("xúrdio", "com forças, cheio de vida, magnífico") );
		db.execSQL( dbh.createInsertDicionario("xurdir", " surgir, alçar-se, aparecer à vista, nascer, discorrer, originar-se algo. lidar com a vida. apressurar-se, apurar, adiantar o trabalho.") );
		db.execSQL( dbh.createInsertDicionario("xurelo", "carapau, peixe da espécie Trachurus trachurus") );
		db.execSQL( dbh.createInsertDicionario("xurro", "enxurro") );
		db.execSQL( dbh.createInsertDicionario("xurumbambo", "cacareco; coisa sem valor; badulaque") );
		db.execSQL( dbh.createInsertDicionario("xurumbambos", " trastes velhos; cacarecos; tarecos.  badulaques.") );
		db.execSQL( dbh.createInsertDicionario("xuxo", "peixe de Portugal. cachucho.") );		
	}
}
