package com.gbraille.keyboard.database;

import android.database.sqlite.SQLiteDatabase;

public class DicionarioPTBRLetraZ {
	public DicionarioPTBRLetraZ(DbHelper dbh, SQLiteDatabase db){
		dicionarioLetraZ(dbh, db);
	}
	
	/* obtido de http://idnael.pegada.net/wikcionario/bd/ - está finalizado */
	private void dicionarioLetraZ(DbHelper dbh, SQLiteDatabase db){
		db.execSQL( dbh.createInsertDicionario("zabaione", "Preparação à base de gemas de ovos, açúcar e álcool.") );
		db.execSQL( dbh.createInsertDicionario("zabelê", "o mesmo que jaó.") );
		db.execSQL( dbh.createInsertDicionario("zabumba", "chapéu alto e grande. tambor grande. zé-pereira.") );
		db.execSQL( dbh.createInsertDicionario("zabumbar", "Atordoar. Bater.") );
		db.execSQL( dbh.createInsertDicionario("zabumbeiro", "Tocador de zabumba.") );
		db.execSQL( dbh.createInsertDicionario("zaburro", " uma variedade de milho indiano.") );
		db.execSQL( dbh.createInsertDicionario("zacá", "Parte dos bens que o Alcorão ordena que se dê aos pobres. O mesmo que azaqui.") );
		db.execSQL( dbh.createInsertDicionario("zaca", "O mesmo que zaco. Um dos tributos que os mouros residentes em Portugal pagavam ao rei.") );
		db.execSQL( dbh.createInsertDicionario("Zacarias", "Prenome masculino. Livro do Velho Testamento. Município brasileiro do estado de São Paulo.") );
		db.execSQL( dbh.createInsertDicionario("zacônio", "Dialeto grego moderno falado em vilarejos na região leste do Peloponeso.") );
		db.execSQL( dbh.createInsertDicionario("zaga", "Conjunto militar que situa-se na retaguarda de uma tropa. A posição dos jogadores de defesa, entre a intermediária e o gol.") );
		db.execSQL( dbh.createInsertDicionario("zagaiar", "Arremessar zagaias. O mesmo que azagaiar.") );
		db.execSQL( dbh.createInsertDicionario("zagal", "Pastor.") );
		db.execSQL( dbh.createInsertDicionario("zagrebino", "Relativo à cidade de Zagreb, Croácia.") );
		db.execSQL( dbh.createInsertDicionario("zagueiro", "No futebol, jogador basicamente encarregado da defesa; beque.") );
		db.execSQL( dbh.createInsertDicionario("zagueiro-central", "Zagueiro que defende a porção central do campo.") );
		db.execSQL( dbh.createInsertDicionario("zagunchar", "Ferir com zaguncho. Molestar; censurar. Dirigir remoques a.") );
		db.execSQL( dbh.createInsertDicionario("zaino", "Cavalo de pelo castanho uniforme. Ouro de pelo negro não brilhante. Velhaco. Sovina.") );
		db.execSQL( dbh.createInsertDicionario("Zaíra", "Nome de mulher.") );
		db.execSQL( dbh.createInsertDicionario("zamba", "Dança e música da Argentina.") );
		db.execSQL( dbh.createInsertDicionario("zambembe", "Mambembe.") );
		db.execSQL( dbh.createInsertDicionario("zambeta", "Que tem as pernas tortas.") );		
		db.execSQL( dbh.createInsertDicionario("zâmbi", "Zumbi.") );
		db.execSQL( dbh.createInsertDicionario("Zâmbia", "País da África, faz fronteira com a República Democrática do Congo, Tanzânia, Malawi, Moçambique, Zimbabwe, Namíbia e Angola.") );
		db.execSQL( dbh.createInsertDicionario("zambiano", "De ou relativo à Zâmbia.") );
		db.execSQL( dbh.createInsertDicionario("zambiense", "Relativo à República da Zâmbia.") );
		db.execSQL( dbh.createInsertDicionario("zambo", "Que tem o caminhar torto, que tem as pernas tortas e roça um pé com outro ao andar.") );
		db.execSQL( dbh.createInsertDicionario("zambra", "Música ou dança mourisca da península Ibérica.") );
		db.execSQL( dbh.createInsertDicionario("zambro", "Que tem as pernas tortas.") );
		db.execSQL( dbh.createInsertDicionario("zambujeiro", "Oliveira brava.") );
		db.execSQL( dbh.createInsertDicionario("Zamora", "Província espanhola da Comunidade autônoma de Castela e Leão. Município e cidade espanhola, capital da província do mesmo nome.") );
		db.execSQL( dbh.createInsertDicionario("zamorano", "De ou relativo a Zamora, Espanha.") );
		db.execSQL( dbh.createInsertDicionario("zanga", "Irritação, raiva.") );
		db.execSQL( dbh.createInsertDicionario("zangado", "De relações cortadas. Que tem zanga. Contrariado; irritado; irado.") );
		db.execSQL( dbh.createInsertDicionario("zangão", "Macho da abelha. Aquele que vive à custa dos outros; parasita; agiota.") );
		db.execSQL( dbh.createInsertDicionario("zangar", "Causar zanga a. Irritar.") );
		db.execSQL( dbh.createInsertDicionario("zangarrear", "Tocar viola à maneira chula, marcando ritmo sempre do mesmo modo e com os mesmos acordes em rasgado.") );
		db.execSQL( dbh.createInsertDicionario("zangarreio", "Ato de zangarrear.") );
		db.execSQL( dbh.createInsertDicionario("zanoio", "Vesgo.") );
		db.execSQL( dbh.createInsertDicionario("zanzar", "Andar sem destino.") );
		db.execSQL( dbh.createInsertDicionario("zanzibarita", "De ou relativo a Zanzibar.") );		
		db.execSQL( dbh.createInsertDicionario("zarabatana", "Tipo de buzina ou porta-voz. tipo de armamento primitivo, constituída por um longo tubo, em geral de madeira, dentro do qual é inserido uma seta ou projétil; arma de uso comum pelos indígenas da América do Sul, onde eram as setas impregnadas de veneno.") );
		db.execSQL( dbh.createInsertDicionario("zarabeto", "Tátaro, pessoa que tem dificuldade no falar.") );
		db.execSQL( dbh.createInsertDicionario("zarafulhar", "Criar confusão, enredar, embrulhar um assunto para que não seja compreendido.") );
		db.execSQL( dbh.createInsertDicionario("zaragalha", "Palavras insubstanciais e ociosas.") );
		db.execSQL( dbh.createInsertDicionario("zaragalhada", "Barulho, desordem, confusão. Enredo, ardil. Mistura remexida de ingredientes numa comida, como na empada ou na morcela.") );
		db.execSQL( dbh.createInsertDicionario("zaragalheiro", "Que tem desordem, desarranjado. Trapaceiro.") );
		db.execSQL( dbh.createInsertDicionario("zaragata", "Desordem, confusão, briga.") );
		db.execSQL( dbh.createInsertDicionario("zaragatoa", "Material absorvente, preso a uma haste, que serve para coletar materiais para exame (através de absorção e atrito), aplicar medicamentos ou limpar cavidades e ferimentos.") );
		db.execSQL( dbh.createInsertDicionario("zaragatoadela", "Ato de zaragatoar.") );
		db.execSQL( dbh.createInsertDicionario("zaralho", "Mulher destituída de personalidade ou desmazelada.") );
		db.execSQL( dbh.createInsertDicionario("zaramalha", "Trapaçaria, embuste, enredo, zaramalhada.") );
		db.execSQL( dbh.createInsertDicionario("zaramalhada", "Trapaçaria, embuste, enredo.") );
		db.execSQL( dbh.createInsertDicionario("zaramalheiro", "que tudo enreda, que faz do simples complexo. mentiroso.") );
		db.execSQL( dbh.createInsertDicionario("zaramelo", "Gago, tátaro.") );
		db.execSQL( dbh.createInsertDicionario("zaranguilhar", "Complicar, confundir, obstruir algo, desarrumar.") );		
		db.execSQL( dbh.createInsertDicionario("zaranza", "Capim do gênero Anthenantia lanata. Pessoa que atua sem tino, atrapalhada, atordoada.") );
		db.execSQL( dbh.createInsertDicionario("zaranzar", "Não ter consistência, atuar sem atenção.") );
		db.execSQL( dbh.createInsertDicionario("zarcão", "Tetróxido de chumbo. Pó vermelho insolúvel em água e em ácidos.") );
		db.execSQL( dbh.createInsertDicionario("zarelhar", "Intrometer-se em tudo; intrigar. Traquinar; doidejar.") );
		db.execSQL( dbh.createInsertDicionario("zargunchada", "Ato de zargunchar.") );
		db.execSQL( dbh.createInsertDicionario("zargunchar", "Bater com zarguncho.") );
		db.execSQL( dbh.createInsertDicionario("zarolho", "Que desvia os olhos em diferente direção, vesgo. Que apenas vê por um olho, torto.") );		
		db.execSQL( dbh.createInsertDicionario("zarpar", "Levantar ferro. Levantar âncora. Partir.") );		
		db.execSQL( dbh.createInsertDicionario("zavar", "Morder raivosamente, com frenesi.") );
		db.execSQL( dbh.createInsertDicionario("zazo", "O grão-sacerdote entre os japoneses.") );
		db.execSQL( dbh.createInsertDicionario("zé", "Indivíduo comum, do povo. Indivíduo sem importância, que não tem peso social.") );		
		db.execSQL( dbh.createInsertDicionario("Zé Doca", "Município brasileiro do estado do Maranhão.") );
		db.execSQL( dbh.createInsertDicionario("zé mané", "Pessoa sem importância.") );
		db.execSQL( dbh.createInsertDicionario("zé-cuecas", "Sujeito inútil. Pacóvio.") );
		db.execSQL( dbh.createInsertDicionario("zé-da-véstia", "Zé-ninguém. Jagodes.") );
		db.execSQL( dbh.createInsertDicionario("zé-dos-anzóis", "fulano; qualquer sujeito.") );
		db.execSQL( dbh.createInsertDicionario("zé-faz-formas", "Jagodes; zé-godes.") );
		db.execSQL( dbh.createInsertDicionario("zé-godes", "Jagodes, Zé-faz-formas.") );
		db.execSQL( dbh.createInsertDicionario("zé-goiaba", "Indivíduo de inteligência ou percepção limitada, incapaz de interagir com outros e com o ambiente à sua volta de maneira eficaz.") );
		db.execSQL( dbh.createInsertDicionario("zé-mané", "Pessoa sem importância.") );
		db.execSQL( dbh.createInsertDicionario("zé-ninguém", "Homem insignificante.") );
		db.execSQL( dbh.createInsertDicionario("zé-pereira", "Tocador de bombo.") );
		db.execSQL( dbh.createInsertDicionario("zé-povinho", "Homem comum, simples, do povo; Zé.") );
		db.execSQL( dbh.createInsertDicionario("zé-quitólis", "homem sem importância.") );
		db.execSQL( dbh.createInsertDicionario("zebra", "Mamífero semelhante ao cavalo que se distingue pelo fato de ter listras pretas ou marrom escuras alternadas com brancas. Resultado inesperado em uma competição esportiva ou da loteria.") );
		db.execSQL( dbh.createInsertDicionario("zebral", "Dizia-se de uma pedra que servia de peso que equivalia a uma arroba. Relativo ou pertencente a zebra.") );		
		db.execSQL( dbh.createInsertDicionario("zebrar", "Listrar, dando a aparência de pele de zebra.") );
		db.execSQL( dbh.createInsertDicionario("zebro", "Cavalo selvagem. Novilho.") );
		db.execSQL( dbh.createInsertDicionario("zebroide", "semelhante à zebra.") );
		db.execSQL( dbh.createInsertDicionario("zebu", "Gado bovino originário da Índia.") );
		db.execSQL( dbh.createInsertDicionario("zebuíno", "Relativo a, da natureza de, ou próprio do zebu.") );		
		db.execSQL( dbh.createInsertDicionario("zéfiro", "Um dos filhos de Aurora e Astreu, sendo seus irmãos Bóreas, Noto e Euro. Foi casado com Íris e vivia numa caverna da Trácia. Era a personificação do vento do oeste.") );
		db.execSQL( dbh.createInsertDicionario("Zeila", "Cidade africana situada no golfo de Adém.") );
		db.execSQL( dbh.createInsertDicionario("zelação", "Ato de zelar. Estrela cadente; meteoro.") );
		db.execSQL( dbh.createInsertDicionario("zelador", "Que zela. Funcionário encarregado da zeladoria, de cuidar de um edifício.") );
		db.execSQL( dbh.createInsertDicionario("zelador-de-inquice", "zelador-de-santo.") );
		db.execSQL( dbh.createInsertDicionario("zelador-de-santo", "chefe temporário de um terreiro de candomblé após a morte do dirigente principal.") );		
		db.execSQL( dbh.createInsertDicionario("zelandês", "de ou relativo à Zelândia, região da Holanda.") );
		db.execSQL( dbh.createInsertDicionario("zelar", "Tomar conta de. Cuidar.") );
		db.execSQL( dbh.createInsertDicionario("zelo", "dedicação ardente, afeição íntima, desvelo, cuidado, interesse.") );		
		db.execSQL( dbh.createInsertDicionario("zeloso", "Que tem zelo. Cuidadoso. Ciumento.") );
		db.execSQL( dbh.createInsertDicionario("zelote", "que finge ter zelo. que finge ser religioso.") );
		db.execSQL( dbh.createInsertDicionario("zen", "variação japonesa do budismo cuja prática consiste, essencialmente, na meditação e autodisciplina.") );
		db.execSQL( dbh.createInsertDicionario("zen-budismo", "escola variante do budismo") );
		db.execSQL( dbh.createInsertDicionario("zen-budista", "adepto do zen-budismo.") );
		db.execSQL( dbh.createInsertDicionario("zen-budístico", "relativo ao zen-budismo ou ao zen-budista") );
		db.execSQL( dbh.createInsertDicionario("zenda", "zende-avesta.") );
		db.execSQL( dbh.createInsertDicionario("zenda-avesta", "zende-avesta.") );
		db.execSQL( dbh.createInsertDicionario("zende", "zende-avesta") );
		db.execSQL( dbh.createInsertDicionario("zende-avesta", "livros sagrados do zoroastrismo persa.") );
		db.execSQL( dbh.createInsertDicionario("zengue-zengue", "nome africano de certa árvore majestosa") );
		db.execSQL( dbh.createInsertDicionario("zênite", "posição mais alta da trajetória de um corpo celeste, do ponto de vista de um observador na Terra.") );		
		db.execSQL( dbh.createInsertDicionario("zenzém", "árvore de grande porte existente em São Tomé cujas folhas são usadas para fins medicinais") );
		db.execSQL( dbh.createInsertDicionario("zepelim", "grande dirigível (de até 245 metros) de armação metálica e sustentação aérea por balões de gás.  peixe com até 5 centímetros de comprimento, nadadeiras vermelhas e corpo recoberto de faixas coloridas.") );
		db.execSQL( dbh.createInsertDicionario("zerar", "tornar zero, sem valor ou sem efeito.") );
		db.execSQL( dbh.createInsertDicionario("zerena-da-groselheira", "mariposa cuja lagarta costuma alimentar-se das folhas de groselheira.") );
		db.execSQL( dbh.createInsertDicionario("zeribanda", "sarabanda. tunda, sova.") );
		db.execSQL( dbh.createInsertDicionario("zero", "cardinalidade do conjunto vazio, o número de elementos de um conjunto que não tem elementos.") );
		db.execSQL( dbh.createInsertDicionario("zero à esquerda", "pessoa insignificante, que não significa absolutamente nada, que não tem nenhum valor.") );
		db.execSQL( dbh.createInsertDicionario("zero-bala", "algo novo, em perfeito estado, bonito, bem de saúde.") );		
		db.execSQL( dbh.createInsertDicionario("zetacismo", "pronúncia viciosa do Z ou do S.") );
		db.execSQL( dbh.createInsertDicionario("zeugo", "instrumento musical constituído de duas flautas unidas.") );
		db.execSQL( dbh.createInsertDicionario("Zeus", "pai dos deuses e dos homens, chefe supremodo Olimpo, filho de Cronos e Réa, irmão e esposo de Hera.") );		
		db.execSQL( dbh.createInsertDicionario("zicha", "campo de cultivo, leira estreita e comprida") );		
		db.execSQL( dbh.createInsertDicionario("zichar", "seringar, sair a pressão um líquido") );
		db.execSQL( dbh.createInsertDicionario("zicheira", "diarreia.") );
		db.execSQL( dbh.createInsertDicionario("zicho", "jato") );
		db.execSQL( dbh.createInsertDicionario("zigoma", "osso da bochecha") );		
		db.execSQL( dbh.createInsertDicionario("zigotactismo", "tactismo referente à atração que ocorre entre dois elementos da reprodução nos vegetais") );
		db.execSQL( dbh.createInsertDicionario("zigoto", "célula formada pela fusão dos gametas masculino e feminino, e que dará origem, por diferenciação e embriogênese, ao novo ser da espécie") );
		db.execSQL( dbh.createInsertDicionario("zigue-zague", "uma linha ou progressão caracterizada por curvas fechadas para um lado e para outro") );
		db.execSQL( dbh.createInsertDicionario("ziguezague", "uma linha ou progressão caracterizada por curvas fechadas para um lado e para outro") );
		db.execSQL( dbh.createInsertDicionario("ziguezaguear", "fazer ziguezagues") );
		db.execSQL( dbh.createInsertDicionario("ziguezigue", " brinquedo infantil que faz um barulho parecido ao da cigarra. libélula.") );
		db.execSQL( dbh.createInsertDicionario("ziguizira", "qualquer doença ou mal-estar que não se sabe o nome.  azar, urucubaca, dificuldade em realizar algo.") );
		db.execSQL( dbh.createInsertDicionario("zigurate", "templo babilônio antigo com plataformas que, sucessivamente recuadas, formam uma construção piramidal") );
		db.execSQL( dbh.createInsertDicionario("zilhão", "um grande número indeterminado de algo.") );
		db.execSQL( dbh.createInsertDicionario("zimbabuano", "habitante ou natural do Zimbabué") );		
		db.execSQL( dbh.createInsertDicionario("Zimbábue", "país africano, faz fronteira com a Zâmbia, Moçambique, África do Sul e Botswana") );
		db.execSQL( dbh.createInsertDicionario("zimbabuense", "natural ou habitante do Zimbábue") );
		db.execSQL( dbh.createInsertDicionario("zimbrar", "açoitar; vergastar. pôr bordões estirados e retesados sobre a pele de (um tambor), para requintar o som. balançar, arfar, da popa à proa, (em se falando de navio).") );
		db.execSQL( dbh.createInsertDicionario("zimbreiro", "o mesmo que zimbro.") );
		db.execSQL( dbh.createInsertDicionario("zimbro", "planta da família das pináceas, comum no norte de Portugal, também chamado genebreiro.") );
		db.execSQL( dbh.createInsertDicionario("zimosimetria", "processo pelo qual se avalia o grau de fermentação dos líquidos.") );
		db.execSQL( dbh.createInsertDicionario("zimoterapia", "método de tratar doenças pelo uso de fermentos.") );
		db.execSQL( dbh.createInsertDicionario("zinabre", "camada verde de carbonato de cobre que se forma nos objetos de cobre expostos ao ar e à umidade.") );
		db.execSQL( dbh.createInsertDicionario("zincar", "revestir de zinco") );
		db.execSQL( dbh.createInsertDicionario("zinco", "elemento químico de símbolo Zn, possui o número atômico 30 e massa atômica relativa 65,409 u. É um metal utilizado principalmente no revestimento (galvanização) de outros metais como o aço e o ferro e, em ligas, como o latão, bronze e ligas especiais para soldas.") );		
		db.execSQL( dbh.createInsertDicionario("zincografar", "gravar ou imprimir em lâminas de zinco") );		
		db.execSQL( dbh.createInsertDicionario("zinga", "vara comprida utilizada por canoeiros para vencer as correntes") );		
		db.execSQL( dbh.createInsertDicionario("zingar", "manejar a zinga") );		
		db.execSQL( dbh.createInsertDicionario("zingarear", "vadiar") );
		db.execSQL( dbh.createInsertDicionario("zingarelho", "qualquer objeto, geralmente complexo, desconhecido, bizarro ou que não funciona bem") );				
		db.execSQL( dbh.createInsertDicionario("zingrar", "dizer motejos. chacotear.") );		
		db.execSQL( dbh.createInsertDicionario("zinguerrear", "emitir um som particular, como coisa que se mova num eixo muito frouxo.") );
		db.execSQL( dbh.createInsertDicionario("zinnwaldita", " mineral composto de potássio, lítio, ferro, silício e alumínio. É obtida associada com outros minerais como o quartzo, a apatita e o feldspato.") );
		db.execSQL( dbh.createInsertDicionario("zipar", " compactar em formato ZIP arquivos no computador utilizando programas compactadores.") );
		db.execSQL( dbh.createInsertDicionario("zíper", "acabamento de fechamento de calças, shorts e vestidos") );
		db.execSQL( dbh.createInsertDicionario("ziquizira", "o mesmo que ziguizira") );
		db.execSQL( dbh.createInsertDicionario("zircônio", " elemento químico de símbolo Zr, possui o número atômico 40 e massa atômica relativa 91,224 u; é um metal de transição branco acinzentado e brilhante; não é encontrado livre na natureza, mas, em associação com outros minerais;") );
		db.execSQL( dbh.createInsertDicionario("ziriguidum", "festa de carnaval") );
		db.execSQL( dbh.createInsertDicionario("zirrar", "fazer zirra-zirra") );
		db.execSQL( dbh.createInsertDicionario("zoar", "zumbir. tirar sarro de alguém; ") );
		db.execSQL( dbh.createInsertDicionario("zodíaco", "zona da esfera celeste onde se acham os doze signos que o Sol parece percorrer num ano.") );
		db.execSQL( dbh.createInsertDicionario("zoéia", "célula de zoóide de colônias de briozoários.") );
		db.execSQL( dbh.createInsertDicionario("zóico", "relativo aos animais, à vida animal.") );
		db.execSQL( dbh.createInsertDicionario("zoilo", "mau crítico; crítico invejoso") );
		db.execSQL( dbh.createInsertDicionario("zola", "o ato de mamar") );
		db.execSQL( dbh.createInsertDicionario("zombador", "que zomba") );
		db.execSQL( dbh.createInsertDicionario("zombar", "debochar, fazer zombaria de") );
		db.execSQL( dbh.createInsertDicionario("zombetear", "o mesmo que zombar") );
		db.execSQL( dbh.createInsertDicionario("zombeteiro", "em que há zombaria; que revela galhofa, troça, ironia ou escárnio") );
		db.execSQL( dbh.createInsertDicionario("zona", " porção de uma superfície esférica, determinada por dois planos paralelos que a cortam.  cada uma das cinco divisões da esfera terrestre.  situação de desordem.  região onde se concentram prostíbulos.") );
		db.execSQL( dbh.createInsertDicionario("zonamento", "ato de zonar") );
		db.execSQL( dbh.createInsertDicionario("zoncá", "idioma sino-tibetano falado no Butão") );
		db.execSQL( dbh.createInsertDicionario("zonchadura", "ato de zonchar") );
		db.execSQL( dbh.createInsertDicionario("zonchar", "operar uma bomba manual através do zoncho") );
		db.execSQL( dbh.createInsertDicionario("zoncho", "que é pequeno e grosso. chorão, esmoleiro.") );
		db.execSQL( dbh.createInsertDicionario("zoneamento", "ato de zonear") );
		db.execSQL( dbh.createInsertDicionario("zonofone", "toca-discos.") );
		db.execSQL( dbh.createInsertDicionario("zonzonar", "soar monotonamente, como o zom-zom da viola") );
		db.execSQL( dbh.createInsertDicionario("zôo", "Zoológico, jardim zoológico.") );
		db.execSQL( dbh.createInsertDicionario("zoo-sanitário", "relativo a aspectos de sanidade animal.") );
		db.execSQL( dbh.createInsertDicionario("zoofilia", "ato de manter relações sexuais com animais") );
		db.execSQL( dbh.createInsertDicionario("zoofobia", "fobia de animais") );
		db.execSQL( dbh.createInsertDicionario("zoogeografia", "ciência que estuda a distribuição geográfica das espécies animais.") );
		db.execSQL( dbh.createInsertDicionario("zoogeógrafo", "pessoa especialista em zoogeografia") );
		db.execSQL( dbh.createInsertDicionario("zoografar", "descrever ou desenhar animais") );
		db.execSQL( dbh.createInsertDicionario("zoolagnia", "atração sexual por animais") );
		db.execSQL( dbh.createInsertDicionario("zoólito", "qualquer fóssil de origem animal") );
		db.execSQL( dbh.createInsertDicionario("zoologia", "ciência biológica que estuda os animais.") );
		db.execSQL( dbh.createInsertDicionario("zoológico", "parque onde se criam e se expoem ao público animais de várias espécies") );
		db.execSQL( dbh.createInsertDicionario("zoólogo", "especialista em zoologia") );
		db.execSQL( dbh.createInsertDicionario("zoonimia", "estudo dos nomes dos animais") );
		db.execSQL( dbh.createInsertDicionario("zoonomia", "fisiologia animal.") );
		db.execSQL( dbh.createInsertDicionario("zoonômico", "relativo a ou próprio da zoonomia.") );
		db.execSQL( dbh.createInsertDicionario("zoopraxioscópio", "aparelho inventado em 1833 para projetar imagens") );
		db.execSQL( dbh.createInsertDicionario("zootáctico", "referente à zootaxia") );
		db.execSQL( dbh.createInsertDicionario("zootecnia", "ciência aplicada e arte de criar animais domesticados") );
		db.execSQL( dbh.createInsertDicionario("zootécnico", "relativo a ou próprio da zootecnia") );
		db.execSQL( dbh.createInsertDicionario("zootecnista", "Aquele que exerce a zootecnia como profissão. Especialista na arte e na ciência de criar animais domésticos.") );
		db.execSQL( dbh.createInsertDicionario("zooxantela", "espécime das zooxantelas, grupo de pirrófitos que vivem em simbiose no interior de vários animais, como, por exemplo, nos corais.") );
		db.execSQL( dbh.createInsertDicionario("zopo", "que se move, que caminha com dificuldade, trôpego") );
		db.execSQL( dbh.createInsertDicionario("zornar", "emitir o som caraterístico o burro ou a burra, zurrar") );
		db.execSQL( dbh.createInsertDicionario("zoró", "Indivíduo do povo indígena tupi-guarani que habita a região de Aripuanã, Mato Grosso, Brasil. Língua mondé falada pelos zorós.") );
		db.execSQL( dbh.createInsertDicionario("zoroastriano", "idioma indo-europeu, do grupo iraniano, falado nas cidades de Yazd e Kerman no Irã Central, assim como em Mumbai na Índia. seguidor do zoroastrianismo.") );
		db.execSQL( dbh.createInsertDicionario("zoroastrismo", "religião monoteísta fundada na antiga Pérsia pelo profeta Zaratustra, com a crença no paraíso, na ressurreição, no juízo final e na vinda de um messias; influenciou o judaísmo, o cristianismo e o islamismo") );
		db.execSQL( dbh.createInsertDicionario("zorra", "ausência de ordem.  prostituta, meretriz, rameira.") );
		db.execSQL( dbh.createInsertDicionario("zorragar", "açoitar, golpear") );
		db.execSQL( dbh.createInsertDicionario("zorrão", "indolente") );
		db.execSQL( dbh.createInsertDicionario("zorregar", "açoitar, golpear, zorragar") );
		db.execSQL( dbh.createInsertDicionario("zorro", "raposo. filho bastardo, enjeitado.") );
		db.execSQL( dbh.createInsertDicionario("zortar", "sair; ir-se embora") );
		db.execSQL( dbh.createInsertDicionario("Zortéa", "município brasileiro do estado de Santa Catarina") );
		db.execSQL( dbh.createInsertDicionario("zoscadoiro", "pau que serve para atiçar as brasas") );
		db.execSQL( dbh.createInsertDicionario("zoscar", "remexer nas brasas ou no lume com um pau para avivá-lo. introduzir um pau num buraco para afugentar um animal. pegar, golpear.") );
		db.execSQL( dbh.createInsertDicionario("zote", "idiota; pateta; parvo; estúpido; ignorante") );
		db.execSQL( dbh.createInsertDicionario("zotismo", "estado ou condição de zote. estupidez; idiotismo.") );
		db.execSQL( dbh.createInsertDicionario("zoupão", "aquele ou aquela que tem pouca habilidade sobretudo no caminhar, que sói tropeçar") );
		db.execSQL( dbh.createInsertDicionario("zoupar", "manotear, dar manotaços, golpear a outro. bater, cair, golpear-se. ") );
		db.execSQL( dbh.createInsertDicionario("zoupeira", "mulher gorda e desajeitada. rameira. intriguista. rodilhona. mentirosa.") );
		db.execSQL( dbh.createInsertDicionario("zoupeirão", "que possui maus costumes, que não se porta de maneira adequada.") );
		db.execSQL( dbh.createInsertDicionario("zoupeiro", "que não pode andar desembaraçado. que tropeça a cada passo por velhice ou incômodo físico. que não é ativo ou desembaraçado.") );
		db.execSQL( dbh.createInsertDicionario("zoupeirona", "mulher mal comportada") );
		db.execSQL( dbh.createInsertDicionario("zoupo", "o mesmo que zopo") );
		db.execSQL( dbh.createInsertDicionario("zoupudo", "pesado, pouco ágil, grosso") );
		db.execSQL( dbh.createInsertDicionario("zoura", "diarreia") );
		db.execSQL( dbh.createInsertDicionario("zourar", "ter diarreia") );
		db.execSQL( dbh.createInsertDicionario("zucar", "bater, soar") );
		db.execSQL( dbh.createInsertDicionario("zuelar", "falar") );
		db.execSQL( dbh.createInsertDicionario("zuir", "fazer ruído. zumbir.") );
		db.execSQL( dbh.createInsertDicionario("zulu", "língua banta falada na África do Sul.") );
		db.execSQL( dbh.createInsertDicionario("zum", "zumbido") );
		db.execSQL( dbh.createInsertDicionario("zumbaiar", "fazer zumbaias a; lisonjear; bajular") );
		db.execSQL( dbh.createInsertDicionario("zumbaieiro", "aquele que faz zumbaias") );
		db.execSQL( dbh.createInsertDicionario("zumbar", " zumbir; fazer zum-zum; fazer ruído. dar pancadas em.") );
		db.execSQL( dbh.createInsertDicionario("zumbi", "o corpo de uma pessoa morta ao qual é dado vida novamente, usualmente para fins maléficos. uma pessoa sem vontade própria, cujas reações são sem vida. uma pessoa semi-morta, ou desfigurada.") );
		db.execSQL( dbh.createInsertDicionario("Zumbi", "nome do último chefe do Quilombo dos Palmares.") );
		db.execSQL( dbh.createInsertDicionario("zumbido", "ruído que fazem os insetos alados ao voarem") );
		db.execSQL( dbh.createInsertDicionario("zumbir", "emitir um sussurro. fazer ruído ou zumbido.") );
		db.execSQL( dbh.createInsertDicionario("zuna", "velocidade, pressa. aversão, antipatia, zúnia. teimosia, obstinação.") );
		db.execSQL( dbh.createInsertDicionario("zungar", "zumbir. silvar.") );
		db.execSQL( dbh.createInsertDicionario("zunge", "o mesmo que bicho-de-pé") );
		db.execSQL( dbh.createInsertDicionario("zungueira", " mulher que percorre as ruas vendendo produtos diversos dentro de uma bacia que leva na cabeça") );
		db.execSQL( dbh.createInsertDicionario("zúnia", "aversão, antipatia") );
		db.execSQL( dbh.createInsertDicionario("zunido", "zumbido") );
		db.execSQL( dbh.createInsertDicionario("zunimento", "ato de zunir") );
		db.execSQL( dbh.createInsertDicionario("zunir", "produzir zunido") );
		db.execSQL( dbh.createInsertDicionario("zunzum", "zumbido. rumor. boato") );
		db.execSQL( dbh.createInsertDicionario("zunzunar", "fazer zun-zum; rumorejar.") );
		db.execSQL( dbh.createInsertDicionario("zupar", "dar golpes, marradas, bater") );
		db.execSQL( dbh.createInsertDicionario("zureta", "adoidado, amalucado. genioso, irascível.") );
		db.execSQL( dbh.createInsertDicionario("Zurique", "maior cidade da Suíça") );
		db.execSQL( dbh.createInsertDicionario("zuriquenho", "de ou relativo à Zurique") );
		db.execSQL( dbh.createInsertDicionario("zuriquense", "de ou relativo à Zurique") );
		db.execSQL( dbh.createInsertDicionario("zurrada", "o mesmo que zurro (voz do burro).") );
		db.execSQL( dbh.createInsertDicionario("zurrapa", "vinho de má qualidade, ou estragado.") );
		db.execSQL( dbh.createInsertDicionario("zurrar", "produzir som (muares como o burro, a mula, o jumento e o jegue).") );
		db.execSQL( dbh.createInsertDicionario("zuruó", " aturdido; atordoado; confuso das ideias; alheio.") );
		db.execSQL( dbh.createInsertDicionario("zurza", "ato de zurzir.") );
		db.execSQL( dbh.createInsertDicionario("zurzidela", "ato ou efeito de zurzir de leve ou uma vez. ato de seviciar por meio de pancadas, murros, chibatadas etc.; espancamento, surra, zurzidura.") );
		db.execSQL( dbh.createInsertDicionario("zurzidura", "ato de zurzir.") );
		db.execSQL( dbh.createInsertDicionario("zurzir", "maltratar, espancar. castigar. repreender energicamente.") );
		db.execSQL( dbh.createInsertDicionario("zuzuto", " que é tolo, pouco inteligente, confuso.") );
	}
}
